import { todayWords } from '../src/data.js'
import { EnglishLevel } from '../server/generated/prisma/enums.js'

export const demoUser = {
  email: 'demo@wordquest.local',
  displayName: 'Mia',
  nativeLanguage: 'zh-CN',
  englishLevel: EnglishLevel.A2,
  targetLevel: EnglishLevel.B1,
  dailyWordCount: 20,
  newWordRatio: 0.75,
  storyGenre: 'adventure',
  timezone: 'Asia/Shanghai',
} as const

export const demoSessionVocabularySeed = todayWords.map((item, index) => ({
  word: item.word.toLowerCase(),
  lemma: item.word.toLowerCase(),
  partOfSpeech: item.pos.replace(/\.$/, ''),
  level: EnglishLevel[item.level as keyof typeof EnglishLevel],
  meaningZh: item.meaning,
  definitionEn: item.definition,
  phoneticUs: item.phonetic,
  phoneticUk: item.phonetic,
  frequencyRank: index + 1,
  exampleSentence: item.example,
  sourceName: 'wordquest-curated',
  sourceLicense: 'internal-curated',
  collection: 'daily-frequency',
  isReview: Boolean(item.review),
}))

const additionalVocabulary = [
  [
    'explore',
    'v',
    '\u63a2\u7d22',
    'to travel through a place to learn about it',
    'They explored the quiet valley.',
    'A2',
  ],
  [
    'memory',
    'n',
    '\u8bb0\u5fc6',
    'the ability to remember information',
    'The song brought back a memory.',
    'A2',
  ],
  [
    'bridge',
    'n',
    '\u6865',
    'a structure built over a river or road',
    'They crossed the stone bridge.',
    'A1',
  ],
  [
    'valley',
    'n',
    '\u5c71\u8c37',
    'low land between hills or mountains',
    'Mist covered the valley.',
    'A2',
  ],
  [
    'record',
    'n',
    '\u8bb0\u5f55',
    'stored information about past events',
    'The journal contained a detailed record.',
    'A2',
  ],
  [
    'notice',
    'v',
    '\u6ce8\u610f\u5230',
    'to become aware of something',
    'Mia noticed a mark on the wall.',
    'A2',
  ],
  ['silent', 'adj', '\u5b89\u9759\u7684', 'making no sound', 'The forest became silent.', 'A2'],
  [
    'search',
    'v',
    '\u5bfb\u627e',
    'to look carefully for something',
    'They searched the old room.',
    'A1',
  ],
  ['return', 'v', '\u8fd4\u56de', 'to go back to a place', 'She returned before sunset.', 'A2'],
  [
    'follow',
    'v',
    '\u8ddf\u968f',
    'to move behind someone or something',
    'Follow the lights along the path.',
    'A1',
  ],
  [
    'forest',
    'n',
    '\u68ee\u6797',
    'a large area covered with trees',
    'The forest was full of birds.',
    'A1',
  ],
  [
    'route',
    'n',
    '\u8def\u7ebf',
    'a way from one place to another',
    'The map showed a safer route.',
    'A2',
  ],
  [
    'arrange',
    'v',
    '\u5b89\u6392',
    'to put things in a planned order',
    'They arranged the stones in a circle.',
    'A2',
  ],
  [
    'unlock',
    'v',
    '\u89e3\u9501',
    'to open something that is locked',
    'The silver key unlocked the gate.',
    'A2',
  ],
  [
    'surface',
    'n',
    '\u8868\u9762',
    'the outside or top layer of something',
    'A symbol appeared on the stone surface.',
    'A2',
  ],
  [
    'clue',
    'n',
    '\u7ebf\u7d22',
    'information that helps solve a problem',
    'The map was their first clue.',
    'A2',
  ],
  [
    'machine',
    'n',
    '\u673a\u5668',
    'a device that uses power to do work',
    'The machine began to hum.',
    'A2',
  ],
  [
    'bright',
    'adj',
    '\u660e\u4eae\u7684',
    'giving out a lot of light',
    'A bright star appeared.',
    'A1',
  ],
  [
    'collect',
    'v',
    '\u6536\u96c6',
    'to bring things together',
    'She collected three blue stones.',
    'A2',
  ],
  ['create', 'v', '\u521b\u9020', 'to make something new', 'They created a simple plan.', 'A2'],
  [
    'danger',
    'n',
    '\u5371\u9669',
    'the possibility of harm',
    'The sign warned them of danger.',
    'A2',
  ],
  [
    'direction',
    'n',
    '\u65b9\u5411',
    'the way something moves or points',
    'The arrow showed the direction.',
    'A2',
  ],
  [
    'event',
    'n',
    '\u4e8b\u4ef6',
    'something that happens',
    'The strange event changed the village.',
    'A2',
  ],
  ['explain', 'v', '\u89e3\u91ca', 'to make an idea clear', 'Mia explained the plan.', 'A2'],
  [
    'future',
    'n',
    '\u672a\u6765',
    'the time that comes after now',
    'The choice may change the future.',
    'A2',
  ],
  [
    'improve',
    'v',
    '\u6539\u5584',
    'to make or become better',
    'Daily practice improves memory.',
    'A2',
  ],
  [
    'language',
    'n',
    '\u8bed\u8a00',
    'a system used for communication',
    'Stories make language memorable.',
    'A2',
  ],
  [
    'prepare',
    'v',
    '\u51c6\u5907',
    'to get ready for something',
    'They prepared for the journey.',
    'A2',
  ],
  [
    'remember',
    'v',
    '\u8bb0\u5f97',
    'to keep an idea in your mind',
    'Remember the blue symbol.',
    'A1',
  ],
  [
    'solution',
    'n',
    '\u89e3\u51b3\u65b9\u6848',
    'an answer to a problem',
    'Together they found a solution.',
    'B1',
  ],
  [
    'challenge',
    'n',
    '\u6311\u6218',
    'a difficult task that tests your ability',
    'The final puzzle was a challenge.',
    'B1',
  ],
  [
    'connect',
    'v',
    '\u8fde\u63a5',
    'to join two or more things together',
    'The tunnel connects the two rooms.',
    'A2',
  ],
  [
    'discoveries',
    'n',
    '\u53d1\u73b0',
    'things found or learned for the first time',
    'They recorded their discoveries in a journal.',
    'B1',
  ],
  [
    'observe',
    'v',
    '\u89c2\u5bdf',
    'to watch something carefully',
    'Mia observed the changing lights.',
    'B1',
  ],
  [
    'pattern',
    'n',
    '\u89c4\u5f8b',
    'a repeated or regular way in which something happens',
    'The symbols formed a clear pattern.',
    'A2',
  ],
  [
    'progress',
    'n',
    '\u8fdb\u6b65',
    'movement toward a better or more complete state',
    'Small daily steps create progress.',
    'A2',
  ],
] as const

export const vocabularySeed = [
  ...demoSessionVocabularySeed,
  ...additionalVocabulary.map(
    ([word, partOfSpeech, meaningZh, definitionEn, exampleSentence, level], index) => ({
      word,
      lemma: word,
      partOfSpeech,
      level: EnglishLevel[level as keyof typeof EnglishLevel],
      meaningZh,
      definitionEn,
      phoneticUs: null,
      phoneticUk: null,
      frequencyRank: demoSessionVocabularySeed.length + index + 1,
      exampleSentence,
      sourceName: 'wordquest-curated',
      sourceLicense: 'internal-curated',
      collection: 'daily-frequency',
      isReview: false,
    }),
  ),
]
